# configuration for ohi-science.shinyapps.io/ecu
study_area:       Ecuador
git_owner:        OHI-Science
git_repo:         ecu
git_slug:         OHI-Science/ecu
git_url:          https://github.com/OHI-Science/ecu
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2014-11-11
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: e1defd965ddbdd884893608a25a0b5dd0a1aedd2

tabs_hide:        
- Calculate
- Report

